import {
  buildLessonReportData,
  buildSelectionHash,
  LESSON_REPORT_VERSION,
} from "@/lib/golf/lesson-report";
import type { LessonReportSnapshot } from "@/lib/golf/round-queries";
import type { RoundSgSnapshot } from "@/lib/golf/trends";
import type { ViewerEntitlements } from "@/lib/billing/entitlements";
import type { RoundDetailSnapshot } from "@/lib/golf/types";

export const previewBuilderEntitlements: ViewerEntitlements = {
  status: "free",
  canGenerateLessonReports: false,
  canViewExistingLessonReports: false,
  expiresAt: null,
  inGracePeriod: false,
};

export const previewReportEntitlements: ViewerEntitlements = {
  status: "premium",
  canGenerateLessonReports: true,
  canViewExistingLessonReports: true,
  expiresAt: "2026-04-10T00:00:00.000Z",
  inGracePeriod: false,
};

export const previewBuilderRounds: RoundSgSnapshot[] = [
  {
    roundId: "preview-round-6",
    playedAt: "2026-03-20",
    courseName: "Riviera",
    score: 83,
    handicapIndex: 13.8,
    sgTotal: 1.2,
    sgOffTheTee: 0.6,
    sgApproach: 0.3,
    sgAroundTheGreen: 0.1,
    sgPutting: 0.2,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
  },
  {
    roundId: "preview-round-5",
    playedAt: "2026-03-16",
    courseName: "Torrey Pines South",
    score: 86,
    handicapIndex: 14.1,
    sgTotal: -0.4,
    sgOffTheTee: -0.2,
    sgApproach: -0.1,
    sgAroundTheGreen: 0.1,
    sgPutting: -0.2,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
  },
  {
    roundId: "preview-round-4",
    playedAt: "2026-03-12",
    courseName: "Pinehurst No. 2",
    score: 81,
    handicapIndex: 13.9,
    sgTotal: 2.1,
    sgOffTheTee: 0.4,
    sgApproach: 1.1,
    sgAroundTheGreen: 0.2,
    sgPutting: 0.4,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
  },
  {
    roundId: "preview-round-3",
    playedAt: "2026-03-08",
    courseName: "Pine Valley GC",
    score: 82,
    handicapIndex: 14.2,
    sgTotal: 1.52,
    sgOffTheTee: 0.8,
    sgApproach: 0.3,
    sgAroundTheGreen: -0.1,
    sgPutting: 0.52,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
  },
  {
    roundId: "preview-round-2",
    playedAt: "2026-03-04",
    courseName: "Pebble Beach Golf Links",
    score: 84,
    handicapIndex: 14.0,
    sgTotal: 0.6,
    sgOffTheTee: 0.3,
    sgApproach: 0.2,
    sgAroundTheGreen: -0.1,
    sgPutting: 0.2,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
  },
  {
    roundId: "preview-round-1",
    playedAt: "2026-03-01",
    courseName: "Pasatiempo",
    score: 88,
    handicapIndex: 14.3,
    sgTotal: -1.3,
    sgOffTheTee: -0.2,
    sgApproach: -0.7,
    sgAroundTheGreen: -0.1,
    sgPutting: -0.3,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
  },
];

const previewDetailRounds: RoundDetailSnapshot[] = [
  {
    roundId: "report-round-1",
    playedAt: "2026-03-01",
    courseName: "Pasatiempo",
    score: 88,
    handicapIndex: 14.3,
    sgTotal: -1.3,
    sgOffTheTee: -0.2,
    sgApproach: -0.7,
    sgAroundTheGreen: -0.1,
    sgPutting: -0.3,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
    benchmarkVersion: "1.1.0",
    benchmarkHandicap: 14.3,
    benchmarkInterpolationMode: "standard",
    calibrationVersion: null,
    totalAnchorMode: null,
    confidenceOffTheTee: "medium",
    confidenceApproach: "high",
    confidenceAroundTheGreen: "medium",
    confidencePutting: "high",
    estimatedCategories: [],
    skippedCategories: [],
    fairwaysHit: 6,
    fairwayAttempts: 14,
    greensInRegulation: 7,
    upAndDownAttempts: null,
    upAndDownConverted: null,
    eagles: 0,
    birdies: 1,
    pars: 6,
    bogeys: 8,
    doubleBogeys: 3,
    triplePlus: 0,
    totalPutts: 33,
    onePutts: null,
    threePutts: null,
    penaltyStrokes: 2,
    courseRating: 72.4,
    slopeRating: 134,
    trustStatus: "trusted",
    trustReasons: [],
    reconciliationScaleFactor: null,
    reconciliationFlags: [],
  },
  {
    roundId: "report-round-2",
    playedAt: "2026-03-04",
    courseName: "Pebble Beach Golf Links",
    score: 84,
    handicapIndex: 14.0,
    sgTotal: 0.6,
    sgOffTheTee: 0.3,
    sgApproach: 0.2,
    sgAroundTheGreen: -0.1,
    sgPutting: 0.2,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
    benchmarkVersion: "1.1.0",
    benchmarkHandicap: 14.0,
    benchmarkInterpolationMode: "standard",
    calibrationVersion: null,
    totalAnchorMode: null,
    confidenceOffTheTee: "medium",
    confidenceApproach: "high",
    confidenceAroundTheGreen: "medium",
    confidencePutting: "high",
    estimatedCategories: [],
    skippedCategories: [],
    fairwaysHit: 7,
    fairwayAttempts: 14,
    greensInRegulation: 8,
    upAndDownAttempts: null,
    upAndDownConverted: null,
    eagles: 0,
    birdies: 2,
    pars: 8,
    bogeys: 6,
    doubleBogeys: 2,
    triplePlus: 0,
    totalPutts: 31,
    onePutts: null,
    threePutts: null,
    penaltyStrokes: 1,
    courseRating: 72.0,
    slopeRating: 130,
    trustStatus: "trusted",
    trustReasons: [],
    reconciliationScaleFactor: null,
    reconciliationFlags: [],
  },
  {
    roundId: "report-round-3",
    playedAt: "2026-03-08",
    courseName: "Pine Valley GC",
    score: 82,
    handicapIndex: 14.2,
    sgTotal: 1.52,
    sgOffTheTee: 0.8,
    sgApproach: 0.3,
    sgAroundTheGreen: -0.1,
    sgPutting: 0.52,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
    benchmarkVersion: "1.1.0",
    benchmarkHandicap: 14.2,
    benchmarkInterpolationMode: "standard",
    calibrationVersion: null,
    totalAnchorMode: null,
    confidenceOffTheTee: "medium",
    confidenceApproach: "high",
    confidenceAroundTheGreen: "medium",
    confidencePutting: "high",
    estimatedCategories: [],
    skippedCategories: [],
    fairwaysHit: 8,
    fairwayAttempts: 14,
    greensInRegulation: 9,
    upAndDownAttempts: null,
    upAndDownConverted: null,
    eagles: 0,
    birdies: 1,
    pars: 8,
    bogeys: 6,
    doubleBogeys: 3,
    triplePlus: 0,
    totalPutts: 32,
    onePutts: null,
    threePutts: null,
    penaltyStrokes: 1,
    courseRating: 72.1,
    slopeRating: 135,
    trustStatus: "trusted",
    trustReasons: [],
    reconciliationScaleFactor: null,
    reconciliationFlags: [],
  },
  {
    roundId: "report-round-4",
    playedAt: "2026-03-12",
    courseName: "Pinehurst No. 2",
    score: 81,
    handicapIndex: 13.9,
    sgTotal: 2.1,
    sgOffTheTee: 0.4,
    sgApproach: 1.1,
    sgAroundTheGreen: 0.2,
    sgPutting: 0.4,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
    benchmarkVersion: "1.1.0",
    benchmarkHandicap: 13.9,
    benchmarkInterpolationMode: "standard",
    calibrationVersion: null,
    totalAnchorMode: null,
    confidenceOffTheTee: "medium",
    confidenceApproach: "high",
    confidenceAroundTheGreen: "medium",
    confidencePutting: "high",
    estimatedCategories: [],
    skippedCategories: [],
    fairwaysHit: 9,
    fairwayAttempts: 14,
    greensInRegulation: 10,
    upAndDownAttempts: null,
    upAndDownConverted: null,
    eagles: 0,
    birdies: 3,
    pars: 9,
    bogeys: 4,
    doubleBogeys: 2,
    triplePlus: 0,
    totalPutts: 30,
    onePutts: null,
    threePutts: null,
    penaltyStrokes: 1,
    courseRating: 72.8,
    slopeRating: 137,
    trustStatus: "trusted",
    trustReasons: [],
    reconciliationScaleFactor: null,
    reconciliationFlags: [],
  },
  {
    roundId: "report-round-5",
    playedAt: "2026-03-16",
    courseName: "Torrey Pines South",
    score: 86,
    handicapIndex: 14.1,
    sgTotal: -0.4,
    sgOffTheTee: -0.2,
    sgApproach: -0.1,
    sgAroundTheGreen: 0.1,
    sgPutting: -0.2,
    methodologyVersion: "3.0.0",
    benchmarkBracket: "10-15",
    benchmarkVersion: "1.1.0",
    benchmarkHandicap: 14.1,
    benchmarkInterpolationMode: "standard",
    calibrationVersion: null,
    totalAnchorMode: null,
    confidenceOffTheTee: "medium",
    confidenceApproach: "high",
    confidenceAroundTheGreen: "medium",
    confidencePutting: "high",
    estimatedCategories: [],
    skippedCategories: [],
    fairwaysHit: 7,
    fairwayAttempts: 14,
    greensInRegulation: 7,
    upAndDownAttempts: null,
    upAndDownConverted: null,
    eagles: 0,
    birdies: 1,
    pars: 7,
    bogeys: 7,
    doubleBogeys: 3,
    triplePlus: 0,
    totalPutts: 34,
    onePutts: null,
    threePutts: null,
    penaltyStrokes: 2,
    courseRating: 75.2,
    slopeRating: 145,
    trustStatus: "trusted",
    trustReasons: [],
    reconciliationScaleFactor: null,
    reconciliationFlags: [],
  },
];

export const previewLessonReportSnapshot: LessonReportSnapshot = {
  id: "preview-report-1",
  userId: "preview-user",
  selectedRoundIds: previewDetailRounds.map((round) => round.roundId),
  selectionHash: buildSelectionHash(
    previewDetailRounds.map((round) => round.roundId),
  ),
  roundCount: previewDetailRounds.length,
  reportVersion: LESSON_REPORT_VERSION,
  generatedAt: "2026-03-18T12:00:00.000Z",
  regeneratedAt: null,
  reportData: buildLessonReportData(previewDetailRounds, {
    generatedAt: "2026-03-18T12:00:00.000Z",
  }),
};
